http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  vehicle:
    host: localhost
    paths: ['/vehicles', '/vehicleTypes', '/vehicleTypes/:typeText']
  vehicleType:
    host: localhost
    paths: []
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  vehicleService:
    url: 'http://localhost:3000'
  vehicleTypeService:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  vehiclePipeline:
    apiEndpoints:
      - vehicle
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: vehicleService
              changeOrigin: 
  vehicleTypePipeline:
    apiEndpoints:
      - vehicleType
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: vehicleTypeService
              changeOrigin: true
